mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^polls/', include('polls.urls', namespace="polls")),
                       url(r'^semis/', include('semis.urls', namespace="semis")),
                       url(r'^admin/', include(admin.site.urls)),
                       )

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
                       url(r"^(?P<question_id>\d+)/result/$", views.results, name='results'),
                       url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
                       )

semis/urls.py
from django.conf.urls import patterns, url
from semis import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login/$', views.login, name='login'),

                       #url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
                       #url(r"^(?P<question_id>\d+)/result/$", views.results, name='results'),
                       #url(r'^(?P<question_id>\d+)/votre/$', views.vote, name='vote'),

                       )

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

semis/models.py
from django.db import models
import locale

class Cost_type_info(models.Model):
    cost_type_id = models.AutoField(primary_key=True)
    cost_type_name = models.CharField(max_length=20)

    def __str__(self):
        return self.cost_type_name


class Project_info(models.Model):
    project_id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=100)

    def __str__(self):
        return self.project_name


class Rank_info(models.Model):
    rank_id = models.AutoField(primary_key=True)
    rank_name = models.CharField(max_length=10)

    def __str__(self):
        return self.rank_name


class Team_info(models.Model):
    team_id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=20)

    def __str__(self):
        return self.team_name


class Level_info(models.Model):
    level_id = models.AutoField(primary_key=True)
    level_name = models.CharField(max_length=10)

    def __str__(self):
        return self.level_name


class Dept_info(models.Model):
    dept_id = models.AutoField(primary_key=True)
    dept_name = models.CharField(max_length=20)

    def __str__(self):
        return self.dept_name


class User_info(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.CharField(max_length=15, null=False)
    password = models.CharField(max_length=20, null=False)
    name = models.CharField(max_length=10, null=False)
    dept_id = models.ForeignKey(Dept_info)
    team_id = models.ForeignKey(Team_info)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=11)
    employee = models.CharField(max_length=15)
    rank_id = models.ForeignKey(Rank_info)
    level_id = models.ForeignKey(Level_info)
    reg_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Pay_info(models.Model):
    pay_id = models.AutoField(primary_key=True)
    id = models.ForeignKey(User_info)
    pay_name = models.CharField(max_length=20)
    card_num = models.CharField(max_length=4, null=True)

    def __str__(self):
        return "{0}[{1}]".format(self.pay_name, self.card_num)


class Spend(models.Model):
    spend_id = models.AutoField(primary_key=True)
    id = models.ForeignKey(User_info)
    cost = models.IntegerField()
    cost_type_id = models.ForeignKey(Cost_type_info)
    reg_date = models.DateTimeField(auto_now_add=True)
    project_id = models.ForeignKey(Project_info)
    comment = models.CharField(max_length=100)
    pay_type = models.ForeignKey(Pay_info)
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{0}[￦{1}, {2}]".format(self.id.name, locale.format('%d', self.cost, 1), self.cost_type_id.cost_type_name)


class Favorite_category(models.Model):
    favorite_id = models.AutoField(primary_key=Team_info)
    id = models.ForeignKey(User_info)
    cost_type_id = models.ForeignKey(Cost_type_info)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from polls.models import Choice, Question


def index(request):
    #latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    #context = {'latest_question_list': latest_question_list}
    context = {'latest_question_list': '123'}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 설문 투표 폼을 다시 보여준다
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a Choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # POST 데이터를 정상적으로 처리하였으면,
        # 항상 HttpResponseRedirect를 반환하여 리다이렉션 처리함
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

semis/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from semis.models import User_info


def index(request):
    context = {'hello': '123'}
    return render(request, 'semis/main.html', context)


def login(request):

    context = {'hello': '123'}
    return render(request, 'semis/login.html', context)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

semis/templates/main/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
ID: <input>
PASSWORD: <input>
</body>
</html>

semis/templates/semis/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Hello world ^^
</body>
</html>

semis/templates/semis/main.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Semis Main</title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
{% block content %}
<h2 class="text-center">Semis</h2>
<form action="{% url 'semis:login' %}" method="post" class="form-horizontal" role="form">
{% csrf_token %}
<div class="container">
  <div class="form-group">
    <label class="control-label col-sm-2 col-md-2 col-lg-2" for="id">ID:</label>
    <div class="col-sm-8">
      <input type="email" class="form-control" id="id" placeholder="Enter Phone Number">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2 col-md-2 col-lg-2" for="pwd">PASSWORD:</label>
    <div class="col-sm-8">
      <input type="password" class="form-control" id="password" placeholder="Enter password">
        <span class=""></span></input>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-md-offset-2 col-sm-10 col-md-2">
      <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-md-offset-2 col-sm-10 col-md-2">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</div>
</form>
{% endblock %}
</body>
</html>

semis/templates/spend/list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>